package com.yomitanmobile.util

import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Katakana loanwords and onomatopoeia, which a novel is full of and which the
 * segmenter has every opportunity to mangle: they carry prolonged-sound marks
 * (コーヒー), small kana (ドキッ), doubled halves (ドキドキ), and many of them
 * are written in hiragana instead (ぐっすり) or take する.
 *
 * Each word is checked twice — alone, and inside a sentence, because in a
 * sentence the surrounding particles decide where longest match starts.
 *
 * Writes `docs/KATAKANA_ONOMATOPOEIA.md`.
 */
class KatakanaOnomatopoeiaTest {

    private data class Case(val word: String, val kind: String, val sentence: String)

    private val cases = listOf(
        // Loanwords: the everyday kind, plus the ones with ー, small kana and ヴ.
        Case("コーヒー", "loanword (long vowels)", "朝はコーヒーを飲む。"),
        Case("ベッド", "loanword (small kana)", "ベッドに寝転がった。"),
        Case("スマートフォン", "loanword (long + small)", "スマートフォンが鳴った。"),
        Case("パソコン", "loanword (clipped)", "パソコンを開く。"),
        Case("ラーメン", "loanword (long vowel)", "ラーメンを食べた。"),
        Case("チョコレート", "loanword (long vowel)", "チョコレートをもらった。"),
        Case("エレベーター", "loanword (two long vowels)", "エレベーターに乗る。"),
        Case("ヴァイオリン", "loanword (ヴ)", "ヴァイオリンを弾く。"),
        Case("アルバイト", "loanword", "アルバイトを始めた。"),
        Case("クラス", "loanword", "クラスの大嫌いな女子。"),
        // Katakana verbs: katakana stem, godan ending in kana.
        Case("サボる", "katakana verb", "授業をサボった。"),
        Case("ググる", "katakana verb", "スマートフォンでググる。"),
        // Onomatopoeia in katakana, including the する form and the small ッ.
        Case("ドキドキ", "onomatopoeia (katakana, doubled)", "心臓がドキドキする。"),
        Case("ワクワク", "onomatopoeia (katakana, doubled)", "遠足がワクワクする。"),
        Case("イライラ", "onomatopoeia (katakana, doubled)", "朱音はイライラした。"),
        Case("ガチャン", "onomatopoeia (katakana, ン)", "ガチャンと音がした。"),
        Case("ドン", "onomatopoeia (short)", "ドンと机を叩いた。"),
        // Onomatopoeia in hiragana — the same words, the other script.
        Case("ぐっすり", "onomatopoeia (hiragana, っ)", "ぐっすり眠った。"),
        Case("にっこり", "onomatopoeia (hiragana, っ)", "にっこり笑った。"),
        Case("ゆっくり", "onomatopoeia (hiragana, っ)", "ゆっくり歩く。"),
        Case("きらきら", "onomatopoeia (hiragana, doubled)", "星がきらきら光る。"),
        Case("ぺこぺこ", "onomatopoeia (hiragana, doubled)", "お腹がぺこぺこだ。"),
        Case("そわそわ", "onomatopoeia (hiragana, doubled)", "そわそわしている。")
    )

    /** Words that could swallow or be swallowed by the cases above. */
    private val distractors = listOf(
        "飲む", "寝る", "鳴る", "開く", "食べる", "乗る", "弾く", "始める",
        "授業", "心臓", "遠足", "机", "叩く", "眠る", "笑う", "歩く", "星",
        "光る", "お腹", "音", "する", "女子", "大嫌い", "朝", "ド", "キ", "ク", "ワ"
    )

    @Test
    fun `katakana words and onomatopoeia survive segmentation`() {
        val lexiconWords = (cases.map { it.word } + distractors).toSet()
        val lexicon = JapaneseTokenizer.Lexicon { it in lexiconWords }

        data class Result(val case: Case, val alone: String?, val inSentence: List<String>)

        val results = cases.map { case ->
            Result(
                case = case,
                alone = JapaneseTokenizer.tokenize(case.word, lexicon).firstOrNull()?.baseForm,
                inSentence = JapaneseTokenizer.tokenize(case.sentence, lexicon).map { it.baseForm }
            )
        }

        val report = buildString {
            appendLine("# Katakana and onomatopoeia")
            appendLine()
            appendLine(
                "Generated by `KatakanaOnomatopoeiaTest`. Each word is segmented twice: on its " +
                    "own, and inside a sentence where the surrounding particles decide where " +
                    "longest match starts. The lexicon also holds single-kana entries (ド, キ, " +
                    "ク, ワ) so that a word chopped in half would show up as such."
            )
            appendLine()
            appendLine("| word | kind | alone | in sentence | sentence segmentation |")
            appendLine("|---|---|---|---|---|")
            for (result in results) {
                val aloneOk = result.alone == result.case.word
                val inSentenceOk = result.case.word in result.inSentence
                appendLine(
                    "| ${result.case.word} | ${result.case.kind} | " +
                        "${if (aloneOk) "ok" else "**${result.alone ?: "none"}**"} | " +
                        "${if (inSentenceOk) "ok" else "**missing**"} | " +
                        "${result.inSentence.joinToString(" / ")} |"
                )
            }
            appendLine()
            val broken = results.filterNot { it.alone == it.case.word && it.case.word in it.inSentence }
            appendLine("**${results.size - broken.size} of ${results.size} words segment correctly.**")
            if (broken.isNotEmpty()) {
                appendLine()
                appendLine("## Not segmented correctly")
                appendLine()
                for (result in broken) {
                    appendLine("- ${result.case.word} (${result.case.kind}): alone → ${result.alone}, sentence → ${result.inSentence}")
                }
            }
        }
        val out = File("../docs/KATAKANA_ONOMATOPOEIA.md").takeIf { it.parentFile.exists() }
            ?: File("docs/KATAKANA_ONOMATOPOEIA.md").also { it.parentFile.mkdirs() }
        out.writeText(report)
        println("[katakana] report written to ${out.absolutePath}")

        val broken = results.filterNot { it.alone == it.case.word && it.case.word in it.inSentence }
        assertTrue(
            "these no longer segment: " + broken.joinToString { "${it.case.word} -> ${it.alone} / ${it.inSentence}" },
            broken.isEmpty()
        )
    }

    @Test
    fun `a doubled onomatopoeia is never counted as its half`() {
        // ドキドキ contains ドキ, and ド and キ are dictionary entries of their
        // own. Longest match must take the whole word.
        val lexicon = JapaneseTokenizer.Lexicon { it in setOf("ドキドキ", "ドキ", "ド", "キ", "する") }
        val bases = JapaneseTokenizer.tokenize("心臓がドキドキする。", lexicon).map { it.baseForm }

        assertTrue(bases.toString(), "ドキドキ" in bases)
        assertTrue(bases.toString(), "ドキ" !in bases)
    }

    @Test
    fun `a katakana word written for emphasis is not cut into a shorter word`() {
        // あいつ spelled アイツ: the dictionary files it under the hiragana, so
        // longest match found アイ ("love") and took it 11 times in one novel.
        val lexicon = JapaneseTokenizer.Lexicon { it in setOf("アイ", "ツ", "嫌い", "は") }
        val bases = JapaneseTokenizer.tokenize("アイツは嫌いだ。", lexicon).map { it.baseForm }

        assertTrue(bases.toString(), "アイ" !in bases)
        assertTrue(bases.toString(), "嫌い" in bases)
    }

    @Test
    fun `a longer katakana word inside a compound is still kept`() {
        // The opposite bias to the two-character rule: ゲーム out of
        // ゲームセンター is the word the reader needs.
        val lexicon = JapaneseTokenizer.Lexicon { it in setOf("ゲーム", "センター", "行く") }
        val bases = JapaneseTokenizer.tokenize("ゲームセンターに行く。", lexicon).map { it.baseForm }

        assertTrue(bases.toString(), "ゲーム" in bases)
    }
}
