package com.yomitanmobile.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF3F51B5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDBE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF00164F)
val md_theme_light_secondary = Color(0xFFC62828)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDAD5)
val md_theme_light_onSecondaryContainer = Color(0xFF410002)
val md_theme_light_tertiary = Color(0xFF2E7D32)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFA5F5A0)
val md_theme_light_onTertiaryContainer = Color(0xFF002106)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44464F)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)

val md_theme_dark_primary = Color(0xFFB4C5FF)
val md_theme_dark_onPrimary = Color(0xFF002A77)
val md_theme_dark_primaryContainer = Color(0xFF263F9A)
val md_theme_dark_onPrimaryContainer = Color(0xFFDBE1FF)
val md_theme_dark_secondary = Color(0xFFFFB4AA)
val md_theme_dark_onSecondary = Color(0xFF690005)
val md_theme_dark_secondaryContainer = Color(0xFF93000B)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD5)
val md_theme_dark_tertiary = Color(0xFF8BD987)
val md_theme_dark_onTertiary = Color(0xFF003910)
val md_theme_dark_tertiaryContainer = Color(0xFF00531B)
val md_theme_dark_onTertiaryContainer = Color(0xFFA5F5A0)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE3E2E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE3E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF44464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC5C6D0)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
